{"name": "Номер заказа появляется в процессе после размещения", "status": "broken", "statusDetails": {"message": "KeyError: 'accessToken'", "trace": "create_user = ('zlewis@example.com', 'x8mOaa#b+J', 'Matthew Lewis', {'message': 'User already exists', 'success': False})\n\n    @pytest.fixture\n    @allure.title(\"Удаляю созданного пользователя\")\n    def delete_user(create_user):\n>       access_token = create_user[3]['accessToken']\nE       KeyError: 'accessToken'\n\nconftest.py:42: KeyError"}, "description": "Создает новый заказ и проверяет, что его номер появился в активных заказах, но не в завершенных.", "parameters": [{"name": "driver", "value": "'firefox'"}], "start": 1733196260381, "stop": 1733196260381, "uuid": "797c08d2-e60b-421c-989e-a6405461a90d", "historyId": "41ab230aa2770914c351815b3434560e", "testCaseId": "b164222954e8075b1d6758b435b00e63", "fullName": "tests.test_order_page.TestOrderPage#test_order_number_appears_in_progress_after_placement", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_order_page"}, {"name": "subSuite", "value": "TestOrderPage"}, {"name": "host", "value": "192.168.1.96"}, {"name": "thread", "value": "76454-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_order_page"}]}